# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datagram.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datagram.proto',
  package='beavertail',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0e\x64\x61tagram.proto\x12\nbeavertail\"\x8f\x01\n\x0c\x44\x61tagramPush\x12\r\n\x05\x62usID\x18\x01 \x01(\t\x12\x16\n\x0epassengerCount\x18\x02 \x01(\r\x12 \n\x18passengerCountConfidence\x18\x03 \x01(\x01\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"l\n\x0b\x44\x61tagramAck\x12\x37\n\x0e\x61\x63knowledgment\x18\x01 \x01(\x0e\x32\x1f.beavertail.DatagramAck.AckType\"$\n\x07\x41\x63kType\x12\x06\n\x02OK\x10\x00\x12\x07\n\x03\x42\x41\x44\x10\x01\x12\x08\n\x04\x42USY\x10\x02\x32K\n\x0cPushDatagram\x12;\n\x04Push\x12\x18.beavertail.DatagramPush\x1a\x17.beavertail.DatagramAck\"\x00\x62\x06proto3'
)



_DATAGRAMACK_ACKTYPE = _descriptor.EnumDescriptor(
  name='AckType',
  full_name='beavertail.DatagramAck.AckType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=248,
  serialized_end=284,
)
_sym_db.RegisterEnumDescriptor(_DATAGRAMACK_ACKTYPE)


_DATAGRAMPUSH = _descriptor.Descriptor(
  name='DatagramPush',
  full_name='beavertail.DatagramPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='busID', full_name='beavertail.DatagramPush.busID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passengerCount', full_name='beavertail.DatagramPush.passengerCount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passengerCountConfidence', full_name='beavertail.DatagramPush.passengerCountConfidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='beavertail.DatagramPush.latitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='beavertail.DatagramPush.longitude', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='beavertail.DatagramPush.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=174,
)


_DATAGRAMACK = _descriptor.Descriptor(
  name='DatagramAck',
  full_name='beavertail.DatagramAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acknowledgment', full_name='beavertail.DatagramAck.acknowledgment', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATAGRAMACK_ACKTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=284,
)

_DATAGRAMACK.fields_by_name['acknowledgment'].enum_type = _DATAGRAMACK_ACKTYPE
_DATAGRAMACK_ACKTYPE.containing_type = _DATAGRAMACK
DESCRIPTOR.message_types_by_name['DatagramPush'] = _DATAGRAMPUSH
DESCRIPTOR.message_types_by_name['DatagramAck'] = _DATAGRAMACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatagramPush = _reflection.GeneratedProtocolMessageType('DatagramPush', (_message.Message,), {
  'DESCRIPTOR' : _DATAGRAMPUSH,
  '__module__' : 'datagram_pb2'
  # @@protoc_insertion_point(class_scope:beavertail.DatagramPush)
  })
_sym_db.RegisterMessage(DatagramPush)

DatagramAck = _reflection.GeneratedProtocolMessageType('DatagramAck', (_message.Message,), {
  'DESCRIPTOR' : _DATAGRAMACK,
  '__module__' : 'datagram_pb2'
  # @@protoc_insertion_point(class_scope:beavertail.DatagramAck)
  })
_sym_db.RegisterMessage(DatagramAck)



_PUSHDATAGRAM = _descriptor.ServiceDescriptor(
  name='PushDatagram',
  full_name='beavertail.PushDatagram',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=286,
  serialized_end=361,
  methods=[
  _descriptor.MethodDescriptor(
    name='Push',
    full_name='beavertail.PushDatagram.Push',
    index=0,
    containing_service=None,
    input_type=_DATAGRAMPUSH,
    output_type=_DATAGRAMACK,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUSHDATAGRAM)

DESCRIPTOR.services_by_name['PushDatagram'] = _PUSHDATAGRAM

# @@protoc_insertion_point(module_scope)
