# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import datagram_pb2 as datagram__pb2


class PushDatagramStub(object):
    """gRPC defines services in this case PushDatagram.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Push = channel.unary_unary(
                '/beavertail.PushDatagram/Push',
                request_serializer=datagram__pb2.DatagramPush.SerializeToString,
                response_deserializer=datagram__pb2.DatagramAck.FromString,
                )


class PushDatagramServicer(object):
    """gRPC defines services in this case PushDatagram.
    """

    def Push(self, request, context):
        """In this service we expose an RPC called Push
        it takes in an DatagramPush and returns an DatagramAck
        dont ask me about the `{}` bc idk :(
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PushDatagramServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Push': grpc.unary_unary_rpc_method_handler(
                    servicer.Push,
                    request_deserializer=datagram__pb2.DatagramPush.FromString,
                    response_serializer=datagram__pb2.DatagramAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beavertail.PushDatagram', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PushDatagram(object):
    """gRPC defines services in this case PushDatagram.
    """

    @staticmethod
    def Push(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/beavertail.PushDatagram/Push',
            datagram__pb2.DatagramPush.SerializeToString,
            datagram__pb2.DatagramAck.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
